### ISSUE TITLE
Support for priority, retry and expire

### ISSUE THREAD

**Issue by siewers** [danesparza/Pushover.NET#1]
It would be nice to have support for priorities etc.

**Comment by danesparza** [comment]
A great idea!  If you'd like to contribute, check out [this guide from GitHub](https://guides.github.com/activities/contributing-to-open-source/)

**Comment by siewers** [comment]
I'm currently working on my own internal library and testing it out. When I'm sattisfied, I'll contribute my implementation to your repo if you'd like?
If my implementation is accepted, I'd might as well switch to Pushover.NET :)

**Comment by siewers** [comment]
By the way, my implementation uses the simple POST parameters, so no dependency on ServiceStack.Text is needed ;)

**Comment by ghost** [comment]
@siewers What happened to your implementation?

**Comment by siewers** [comment]
@voltagex My goodness I completely forgot about it :(
Unfortunately I never had the chance to finish my implementation, and have since then moved on to other projects.
I'll see if I still have the code, as it was never committed anywhere.
IIRC it wasn't that much of a change to the codebase, but I believe I was working towards a fluent interface for building notifications.

**Comment by danesparza** [comment]
@siewers Thanks for the follow up!  Let me know if you need any help with the integration

**Comment by diggforbeer** [comment]
Just saw this wasnt implemented and I am interested in it.  I will get you a pull-request soon if youll merge it in.

**Comment by danesparza** [comment]
Sounds good! I look forward to merging it

**Comment by danesparza** [comment]
Reviewed and merged associated pull request
