### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by rogerfar** [danesparza/Pushover.NET#2]
I installed this lib because it was in Nuget, but I get a 400 error. Is this library still relevant?

**Comment by danesparza** [comment]
Hmmm ... I think it should still work.  I just double checked the [endpoint the our library](https://github.com/danesparza/Pushover.NET/blob/master/PushoverClient/Pushover.cs#L15) against the [endpoint in the API docs](https://pushover.net/api), and that looks the same.  

Have you [contacted Pushover support](https://pushover.net/support)?

**Comment by Biztactix-Ryan** [comment]
I'm getting the same thing... 400 Error...
Was going to use this... but might move to another service.
_______________________________________________________
Ryan Tregea
<a href="https://biztactix.com.au">Biztactix</a>

**Comment by juergenhoetzel** [comment]
I also encountered this issue. Errors are not handled by the current implementation, because they throw an `WebException`. A added an Exception handler, so error-responses are returned as `PushResponse`  (I suppose this was the intent of @danesparza).

Result in F# interactive:


```
val it : PushResponse =
  PushoverClient.PushResponse {Errors = seq ["application token is invalid"];
                               Request = "af6571677cdec5dc58d73f433a7ec5ac";
                               Status = 0;}
```
